FROM python:3.12-alpine3.18 AS requirements

RUN pip install poetry-plugin-export

WORKDIR /code

COPY pyproject.toml poetry.lock ./

RUN poetry export --without-hashes --format=requirements.txt > requirements.txt


FROM python:3.12-alpine3.18

WORKDIR /code

COPY --from=requirements /code/requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir