# Generated by Django 5.1.7 on 2025-03-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_user_alter_countdown_target_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=150, unique=True)),
                ('users', models.ManyToManyField(to='countdown.user')),
            ],
        ),
    ]
