# Generated by Django 5.1.7 on 2025-03-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0004_session_busy_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionUserQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countdown.session')),
                ('latest_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countdown.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countdown.user')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='session_user_questions',
            field=models.ManyToManyField(to='countdown.sessionuserquestions'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_User_Questions',
            field=models.ManyToManyField(to='countdown.sessionuserquestions'),
        ),
    ]
