# Generated by Django 5.1.7 on 2025-03-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0005_sessionuserquestions_question_session_user_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sessionuserquestions',
            name='new_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_question', to='countdown.question'),
        ),
        migrations.AlterField(
            model_name='sessionuserquestions',
            name='latest_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_question', to='countdown.question'),
        ),
    ]
