# Generated by Django 5.1.7 on 2025-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0006_session_round_sessionuserquestions_new_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='busy',
        ),
        migrations.AddField(
            model_name='session',
            name='target_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
